# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-07 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apis',
            fields=[
                ('id', models.AutoField(max_length=5, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(max_length=100, verbose_name='URL')),
                ('name', models.CharField(max_length=20, verbose_name='接口名称')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], default='POST', max_length=10)),
                ('params', models.TextField(max_length=5000)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('status', models.BooleanField(verbose_name='状态')),
            ],
            options={
                'verbose_name': '接口列表',
                'verbose_name_plural': '接口列表',
            },
        ),
    ]
