# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-07-10 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 50, 4, 644395), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='case',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 50, 4, 644395), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 50, 4, 645413), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 50, 4, 646412), verbose_name='创建时间'),
        ),
    ]
