# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-07-10 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20190710_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='last_do_time',
            field=models.DateTimeField('上次执行时间', null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apis',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 51, 21, 225900), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='case',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 51, 21, 226901), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 51, 21, 227900), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 51, 21, 227900), verbose_name='创建时间'),
        ),
    ]
