# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-07-10 17:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20190710_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 55, 6, 24166), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='case',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 55, 6, 25164), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 55, 6, 25164), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 55, 6, 26166), verbose_name='创建时间'),
        ),
    ]
