# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-07-11 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_auto_20190710_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='do_times',
            field=models.CharField(default='0', max_length=10, verbose_name='执行次数'),
        ),
        migrations.AlterField(
            model_name='apis',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 9, 56, 49, 621740), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='case',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 9, 56, 49, 622740), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 9, 56, 49, 623740), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 9, 56, 49, 624739), verbose_name='创建时间'),
        ),
    ]
