# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-12 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_auto_20190711_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunRecord',
            fields=[
                ('id', models.AutoField(max_length=5, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_ids', models.CharField(max_length=500, verbose_name='执行任务ID')),
                ('spend_time', models.CharField(max_length=50, verbose_name='执行时间')),
                ('schedule_result', models.CharField(choices=[('Success', '成功'), ('Fail', '失败')], max_length=20, verbose_name='执行结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=20, verbose_name='用例名称'),
        ),
    ]
