# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0007_auto_20190812_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrecord',
            name='fail_count',
            field=models.IntegerField(default=0, verbose_name='失败数'),
        ),
        migrations.AddField(
            model_name='runrecord',
            name='success_count',
            field=models.IntegerField(default=0, verbose_name='成功数'),
        ),
        migrations.AddField(
            model_name='runrecord',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='用例总数'),
        ),
    ]
