# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-12 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0008_auto_20190812_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrecord',
            name='sequence',
            field=models.CharField(max_length=100, null=True, verbose_name='执行序列号'),
        ),
    ]
