# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0010_auto_20190813_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=200, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_status',
            field=models.CharField(default='未执行', max_length=10, verbose_name='执行状态'),
        ),
    ]
